Restoring training reference guidelines
mlcommons/training_policies pull request #475
Opened 2021-11-02 16:08 UTC by johntran-nv

Guenther mistakenly deleted our guidelines for contributing to training references when he updated all the contributing documents, but we actually use this, so I'm restoring it here.  No content changes from the previous version.

2021-11-02 16:23 UTC, guschmue requested changes

2021-11-02 16:23 UTC, guschmue commented on CONTRIBUTING.md
> + 2. The target accuracy threshold needs to be explicit in the README and [MLPerf rules doc](https://github.com/mlperf/training_policies/blob/master/training_rules.adoc#3-benchmarks "benchmark table")
s/mlperf/mlcommons/

2021-11-02 16:23 UTC, guschmue commented on CONTRIBUTING.md
> + 5. Execution should be deterministic if possible, following rules established in the [convergence document](https://docs.google.com/document/d/15DBV5mM8KHYMjGRsJiztQaz-uxKaekOr2pnwmQl_RT0/edit#headi
link is not public

2021-11-04 15:54 UTC, johntran-nv commented on CONTRIBUTING.md
> + 5. Execution should be deterministic if possible, following rules established in the [convergence document](https://docs.google.com/document/d/15DBV5mM8KHYMjGRsJiztQaz-uxKaekOr2pnwmQl_RT0/edit#headi
@petermattson , I believe this was your google doc, and permissions have been retracted.  Could you move it to the mlcommons repo or shared drive and update the link?

2021-11-04 15:58 UTC, johntran-nv commented on CONTRIBUTING.md
> + 2. The target accuracy threshold needs to be explicit in the README and [MLPerf rules doc](https://github.com/mlperf/training_policies/blob/master/training_rules.adoc#3-benchmarks "benchmark table")
Thanks for catching this, @guschmue .  I fixed these two and a third one below now.
https://github.com/mlcommons/training_policies/pull/475/commits/075f57ef937c2e890882d326aa98ed06716ca88b

2021-11-04 16:07 UTC, guschmue approved these changes

2021-11-04 16:08 UTC, merged