[SSD] Updated rules for v2.0
mlcommons/training_policies pull request #484
Opened 2022-02-06 15:13 UTC by ahmadki

2022-02-16 23:32 UTC, qpjaada commented on training_rules.adoc
> +| |Object detection (light weight) |SSD |34.0% mAP
Should we atleast include the name `Retinanet` in parentheses here? - cause SSD could mean a very specific model different from Retinanet to some folks

2022-02-16 23:49 UTC, qpjaada commented on training_rules.adoc
> + |ssd |adam |global_batch_size |arbitrary constant |reference --batch-size |link:https://github.com/mlperf/training/blob/master/single_stage_detector/ssd/train.py#L82[reference code]
all the links to the reference code seem to be pointing to some old outdated code...

2022-02-16 23:56 UTC, qpjaada commented on training_rules.adoc
> + |ssd |adam |opt_base_learning_rate |unconstrained |base learning rate, this should be the learning rate after warm up and before decay |link:https://github.com/mlperf/training/blob/master/single_sta
do we need to be explicit here that the `beta` values and `weight-decay` for the Adam optimizer are constrained?

2022-02-16 23:57 UTC, qpjaada requested changes
Looks good - just requesting to update some of the links to the reference code.

2022-02-17 06:25 UTC, emizan76 commented on training_rules.adoc
> + |ssd |adam |opt_base_learning_rate |unconstrained |base learning rate, this should be the learning rate after warm up and before decay |link:https://github.com/mlperf/training/blob/master/single_sta
Yes, I think it is better to be explicit, because a submitter may think that because the hparam is missing from the table then they can vary it arbitrarily.

2022-05-05 15:58 UTC, johntran-nv commented
Training WG approves.  

But before we merge, @ahmadki is the question on outdated reference links still relevant?

2022-05-15 03:19 UTC, ahmadki commented on training_rules.adoc
> +| |Object detection (light weight) |SSD |34.0% mAP
done

2022-05-15 03:19 UTC, ahmadki commented on training_rules.adoc
> + |ssd |adam |global_batch_size |arbitrary constant |reference --batch-size |link:https://github.com/mlperf/training/blob/master/single_stage_detector/ssd/train.py#L82[reference code]
Fixed after the RetinaNet code was merged.
Links were updated after recent code changes

2022-05-15 03:21 UTC, ahmadki commented on training_rules.adoc
> + |ssd |adam |opt_base_learning_rate |unconstrained |base learning rate, this should be the learning rate after warm up and before decay |link:https://github.com/mlperf/training/blob/master/single_sta
Done for `opt_weight_decay`.
`beta`will require updating the logger/checker and the reference code, so will be done in v2.0+

2022-05-16 18:56 UTC, merged