Include llm training rules
mlcommons/training_policies pull request #514
Opened 2023-02-08 08:05 UTC by ShriyaPalsamudram

High level list of rule changes
1. Minimum number of GPUs needed to train an llm reference
2. LLM metadata preprocessing need not be timed
3. Add quality metric, dataset, model details, hyperparameters and constraints
4. Add note on fixed learning rate and restrictions on hparams search
5. RCP generation exception and timeline

2023-02-09 16:45 UTC, sgpyc commented on training_rules.adoc
> +| |Large language model |C4 3.0.1
"C4 3.0.1" -> "C4/en/3.0.1"?

2023-02-09 16:47 UTC, nv-rborkar commented
Training WG meeting 02/09: @itayhubara @sgpyc assigned for review

2023-02-09 16:50 UTC, sgpyc commented on training_rules.adoc
> + |llm |adam |opt_adam_epsilon |0.1 |adam epsilon |See PR (From NV and Google, TODO Link)
opt_adam_epsilon = 1e-8

2023-02-09 16:57 UTC, sgpyc commented on training_rules.adoc
> + |llm |adam |opt_gradient_accumulation_steps |unconstrained |Numer of fwd/bwd steps between optimizer step. |See PR (From NV and Google, TODO Link)
Every benchmark has this value, and the name is "gradient_accumulation_steps".
Maybe we can skip it here?

2023-02-09 17:27 UTC, sgpyc commented on training_rules.adoc
> + |llm |adam |opt_learning_rate_decay_steps |ceil(108600 * 1536 / global_batch_size) |learning rate cosine decay from (opt_learning_rate_warmup_steps + 1,opt_learning_rate_decay_steps]. |See PR (From
May be add "the step at which the end of the cosine learning rate curve is reached."?

2023-02-09 17:28 UTC, sgpyc commented on training_rules.adoc
> +|        |large Language Model |GPT-3| Every 24576 samples. CEIL(24576 / global_batch_size) if 24576 is not divisible by GBS
"samples" => "sequences"?

2023-02-13 15:01 UTC, itayhubara commented
Looks good to me I would consider adding that dropout is zero: attention-dropout 0.0, hidden-dropout 0.0

2023-02-14 19:57 UTC, ShriyaPalsamudram commented on training_rules.adoc
> + |llm |adam |opt_gradient_accumulation_steps |unconstrained |Numer of fwd/bwd steps between optimizer step. |See PR (From NV and Google, TODO Link)
I think that it is still good to explicitly report the value even though it can be computed manually.

2023-02-16 16:41 UTC, sgpyc commented on training_rules.adoc
> +* For (3073,4096) - opt_base_learning_rate=2.0e-5 or opt_base_learning_rate=3.0e-5
`(3073, 4096)` => `(3072, 4096)`

2023-02-16 16:42 UTC, sgpyc commented on training_rules.adoc
> +|        |large Language Model |GPT-3| Every 24576 samples. CEIL(24576 / global_batch_size) if 24576 is not divisible by GBS
`samples` => `sequences`

2023-02-16 16:42 UTC, sgpyc commented on training_rules.adoc
> +| LLM | Training sample starting from 0 (integer)
`sample` => `token` ?

2023-02-16 17:02 UTC, ShriyaPalsamudram commented on training_rules.adoc
> +|        |large Language Model |GPT-3| Every 24576 samples. CEIL(24576 / global_batch_size) if 24576 is not divisible by GBS
Fixed in commit: e996e70

2023-02-16 17:04 UTC, sgpyc commented on training_rules.adoc
> +| GPT3 | Training sample starting from 0 (integer)
`sample` => `token` ?

2023-02-16 17:06 UTC, sgpyc requested changes
Looks good after comments are resolved.

2023-02-16 18:27 UTC, johntran-nv commented
Training WG approved today.

2023-02-16 18:29 UTC, merged